### ISSUE TITLE
Seems to have an impact on performance

### ISSUE THREAD

**Issue by jorgeperezlara** [tuberry/user-theme-x#10]
When in dark mode (and only there), Gnome seems to be dropping frames on my computer. You can notice by a subtle fade, which is how Gnome is hiding the dropped frames.

This is my neofetch capture:

OS: Fedora Linux 38 (Workstation Edition) x86_64 
Host: G5 KD 
Kernel: 6.3.11-200.fc38.x86_64 
Uptime: 5 mins 
Packages: 10126 (rpm), 778 (flatpak) 
Shell: bash 5.2.15 
Resolution: 1920x1080 
DE: GNOME 44.2 
WM: Mutter 
WM Theme: Adwaita 
Theme: Adwaita [GTK2/3] 
Icons: Adwaita [GTK2/3] 
Terminal: gnome-terminal 
CPU: 11th Gen Intel i5-11400H (12) @ 4.500GHz 
GPU: Intel TigerLake-H GT1 [UHD Graphics] 
GPU: NVIDIA GeForce RTX 3060 Mobile / Max-Q 
Memory: 4384MiB / 15758MiB

**Comment by tuberry** [comment]
This extension only modifies the corresponding settings and does not involve expensive performance consumption, so I think you're referring to the harmless [transition](https://github.com/tuberry/user-theme-x/blob/7baeef3b822f771b1272b7b914c1b0f7b9ef201f/src/extension.js#L94C1-L94C1) on switching. You can comment out this line of code and reboot to see if the problem is solved.

**Comment by jorgeperezlara** [comment]
It seems I've found out what's going on finally. There's something triggering from time to time that transition to happen. **It only occurs when in dark mode**.  There seems to be some kind of bug in there, and only when I disable the extension, it happens. I could, of course, comment out the transition and call it a day, but I believe there's some kind of bug that maybe should be addressed.

Let me attach a video of the problem. I was only able (this time) to make it appear when I was in 
[Fading_issues.webm](https://github.com/tuberry/user-theme-x/assets/27703624/edba64d8-6bbf-4951-bbae-15ba0965b4a2)

**Comment by tuberry** [comment]
This seems to be how the transition works, i.e. caching screen content then fading it out. So the screen looks like it's dropping frames when dynamic content is presented (like playing videos). 

Can you reproduce the issue when disabling this extension and clicking the `Dark Style` button in the system menu?

**Comment by jorgeperezlara** [comment]
Nope, I'm not able to. To be clear, there's a smooth transition between the `Light Style` and the `Dark Style`, but that's it. As you can see in the video I attached, it happens **after** the transition to dark mode has occurred. I believe the extension might be triggering this behavior when it's not actually intended to do so.

**Comment by tuberry** [comment]
That's a little weird. Disabling the extension should not trigger the transition. I still can't reproduce this issue (on GNOME 46), or I can't tell with my naked eyes that the frame rate with this extension enabled in dark mode is lower than in light mode.  So:
1. Can you reproduce the issue on GNOME 45/46?
2. Can you confirm that deleting the transition will fix the issue for you?
