### ISSUE TITLE
Changed the theme mode, the shell theme did not change

### ISSUE THREAD

**Issue by XiaoJiang0208** [tuberry/user-theme-x#12]
I change the night mode but my shell did not change
![image](https://github.com/tuberry/user-theme-x/assets/65716862/dba74bb8-04f6-47a1-83ae-7ff42088a78f)

**Comment by tuberry** [comment]
> I change the night mode but my shell did not change

Do you mean the [Night Light](https://github.com/tuberry/user-theme-x/issues/11#issuecomment-1727334261)?

Can't reproduce, if the other settings (`Style`/`Icons`...) work fine, it may be conflicting with other analogous extensions, like [user-theme](https://extensions.gnome.org/extension/19/user-themes/), try turning them off.

**Comment by XiaoJiang0208** [comment]
Yes, the other settings (Style/Icons...) work fine. I try to removed user-theme but still not working. Is it a problem with the ubuntu?

**Comment by tuberry** [comment]
Sorry for late.

What version of GNOME Shell are you using? Could you try changing the Shell theme using user-theme with this extension disabled?

**Comment by XiaoJiang0208** [comment]
I can change it, but it can't change by itself. Shell theme always in light mode, but others is changed.

**Comment by tuberry** [comment]
You can get GNOME Shell version by running `gnome-shell --version` in the terminal, by the way, versions older than 45 are no longer supported.

If you're using GNOME 45, you could:
1. download the patched version [gnome-shell-extension-user-theme-x_v35.zip](https://github.com/tuberry/user-theme-x/files/13823131/gnome-shell-extension-user-theme-x_v35.zip);
2. run `gnome-extensions install --force ~/Dowloads/gnome-shell-extension-user-theme-x_v35.zip` to install, then re-login to take effect;
3. turn off any other extensions;
4. run `journalctl -fo cat /usr/bin/gnome-shell` in the terminal, then adjust the Night Light time like [night-light-screencast.webm](https://github.com/tuberry/user-theme-x/assets/17917040/023ac8a2-f1d4-4214-9f27-8a71807a6ea2);
5. show me the related logs.
