### ISSUE TITLE
Feature request: accent colours

### ISSUE THREAD

**Issue by petar-v** [tuberry/user-theme-x#15]
Hello!

Thank you so much for this extension, it's fantastic, and I use it daily to switch between dark and light style. 

Now, with Gnome 47, it would be really nice if we can change the accent colours for dark and light themes. I am happy to have a go and try to implement that, but is this something you'd like to merge in? 

Thanks!

**Comment by tuberry** [comment]
Sounds great and I would like to see that.
 
Thanks!

**Comment by petar-v** [comment]
Fantastic, great to know! I currently don't have enough time to start this anytime soon, but I thought it would be good to put the idea out there. If anyone else wants to have a go, that'd be great :)

**Comment by tuberry** [comment]
For those who want to try it out, accent colors and light/dark styles are not strongly correlated, for example there are users who would like to sync the accent color with the wallpaper like [Material You](https://github.com/FrancescoCaracciolo/material-you-colors), so this feature would be better implemented to be toggled separately.

**Comment by petar-v** [comment]
Hey @tuberry, thank you so much for adding this, this is awesome! :D
