### ISSUE TITLE
Add configurable keyboard shortcut for toggling the style

### ISSUE THREAD

**Issue by nixigaj** [tuberry/user-theme-x#18]
As the title states, it would be nice to be able to toggle the style using a configurable global keyboard shortcut, similar to Night Theme Switcher: 
![Screenshot from 2024-12-07 13-24-37](https://github.com/user-attachments/assets/54ab63dc-5c35-4f7d-ab8a-f276f38bc80b)

**Comment by tuberry** [comment]
Sorry, this extension is dedicated to switching styles [automatically](https://gitlab.gnome.org/GNOME/gnome-control-center/-/issues/2060), as for manual switching I recommend using the Night Theme Switcher + [DM Theme Changer](https://extensions.gnome.org/extension/7379/dm-theme-changer/).
