### ISSUE TITLE
我装了Input Method Panel 扩展,自定义样式对此扩展不起作用.

### ISSUE THREAD

**Issue by yueduz** [tuberry/user-theme-x#2]
扩展地址 <http://github.com/wengxt/kimpanel-for-gnome-shell>

**Comment by tuberry** [comment]
各扩展会加载各自的样式表，不起作用是预期行为。

**Comment by yueduz** [comment]
但是css不是可以被后来的覆盖吗？

**Comment by tuberry** [comment]
扩展样式属于 custom ，优先级高。按你的理解任何扩展的样式都比我这个后加载。请到相应的的 repo 提 issue。

**Comment by tuberry** [comment]
现在也许能起作用。

**Comment by yueduz** [comment]
> 现在也许能起作用。

起作用了,非常感谢!
