### ISSUE TITLE
How to know when wallpaper time will change from day/night? 

### ISSUE THREAD

**Issue by Scotty-Trees** [tuberry/user-theme-x#8]
![Screenshot from 2022-06-01 00-04-46](https://user-images.githubusercontent.com/45135187/171325328-3c0322c2-af87-4f24-9de8-8bb55728f1ef.png)

Greetings, and thanks for creating this extension. I just have one quick question. When I select a day and night time wallpaper, how exactly do I know what time it will change from day time to night time? It doesn't seem to be based on my Night Light time, so I'm wondering how your extension knows when to change from day time wallpaper to night time wallpaper. I don't know if it's suppose to be reading my Night Light time or not or if it's based on my location or if it's defaulted to some time values you gave it, I am not sure. Would appreciate any clarification thank you.

**Comment by tuberry** [comment]
It's based on Night Light. There is a 1-hour-long gradual change process, see https://gitlab.gnome.org/GNOME/gnome-settings-daemon/-/issues/125

**Comment by tuberry** [comment]
More precisely, the wallpaper changes with the Style (the Dark Mode scheme in Settings), while the Style changes with the Night Light (If you enabled `Theme` auto switch in this extension).

**Comment by Scotty-Trees** [comment]
Thanks for the replies. I keep my theme in Gnome 42 to always be the Dark style, I never use the light style. And I have my Night Light set to ON to "Manual Schedule" from 9:00PM to 7:00AM. The image above is my current settings for your extension. Do I need to adjust anything else on my end or should when it comes to 7:00AM tomorrow, my light wallpaper will be displayed? I tried it briefly last night, but noted no wallpaper change, so I wasn't sure if I had the right settings for it.

**Comment by tuberry** [comment]
That's expected. The wallpaper setting here is just create an XML file like [this](https://www.debugpoint.com/2022/04/custom-light-dark-wallpaper-gnome/). Gnome Shell will change wallpaper based on the XML file and the Dark/Light style.

**Comment by Scotty-Trees** [comment]
Okay, I'll keep the extension ON and see if tomorrow after 7:00AM if it does indeed change my wallpaper to the light version. Hopefully it works. If you don't hear back from me tomorrow, it just means it's working on my end, otherwise I'll update you tomorrow on any issues I may come across. And thank you for all the replies, I appreciate you taking the time to explain this all to me.

**Comment by tuberry** [comment]
Cannot reproduce:

https://user-images.githubusercontent.com/17917040/171779992-f7389cbd-1b8a-482f-a75a-cc2c1678de2d.mp4

**Comment by Scotty-Trees** [comment]
for your app the "Stylesheet" it says 'Load from "~/.config/gnome-shell/gnome-shell{-dark}.css" but I do not have a gnome-shell folder in my .config file. Could this be part of my issue maybe? I still can't get it to change wallpaper when night light goes on or off.

**Comment by tuberry** [comment]
> Could this be part of my issue maybe? 

You should create it on your own, see https://github.com/tuberry/user-theme-x#stylesheet

> I still can't get it to change wallpaper when night light goes on or off

You should set `Style` themes auto-switch under the `Wallpaper` as the screencast shows. The `Wallpaper` does not directly change with the Night Light, but with the `Style`.
