### ISSUE TITLE
How to remove?

### ISSUE THREAD

**Issue by cwells** [tuberry/user-theme-x#9]
Installed via extensions.gnome.org, but after uninstalling, default theme is ruined. Some apps are light mode (Brave, Sakura, vscode), some are dark. Wrong icons are used.

What changes are made so that I can try to undo them? 

Fedora 37/GNOME 43

**Comment by tuberry** [comment]
```bash
dconf reset /org/gnome/desktop/interface/color-scheme
dconf reset /org/gnome/desktop/interface/cursor-theme
dconf reset /org/gnome/desktop/interface/gtk-theme
dconf reset /org/gnome/desktop/interface/icon-theme
```

**Comment by cwells** [comment]
thank you so much
